"""initial schema: departments, users, workers, tools, consumables, lendings

Revision ID: 66ba7c1819b7
Revises:
Create Date: 2026-07-01 19:27:55.737565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66ba7c1819b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('consumables',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumables_barcode'), 'consumables', ['barcode'], unique=True)
    op.create_index(op.f('ix_consumables_department_id'), 'consumables', ['department_id'], unique=False)
    op.create_table('tools',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sa.Enum('VERFUEGBAR', 'AUSGELIEHEN', 'DEFEKT', 'AUSGEMUSTERT', name='toolstatus'), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_barcode'), 'tools', ['barcode'], unique=True)
    op.create_index(op.f('ix_tools_department_id'), 'tools', ['department_id'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MITARBEITER', name='userrole'), nullable=False),
    sa.Column('auth_source', sa.Enum('LOCAL', 'LDAP', 'SSO', name='authsource'), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workers',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_barcode'), 'workers', ['barcode'], unique=True)
    op.create_index(op.f('ix_workers_department_id'), 'workers', ['department_id'], unique=False)
    op.create_table('consumable_usages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consumable_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_usages_consumable_id'), 'consumable_usages', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_usages_used_at'), 'consumable_usages', ['used_at'], unique=False)
    op.create_index(op.f('ix_consumable_usages_worker_id'), 'consumable_usages', ['worker_id'], unique=False)
    op.create_table('lendings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('lent_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lendings_department_id'), 'lendings', ['department_id'], unique=False)
    op.create_index(op.f('ix_lendings_lent_at'), 'lendings', ['lent_at'], unique=False)
    op.create_index(op.f('ix_lendings_returned_at'), 'lendings', ['returned_at'], unique=False)
    op.create_index(op.f('ix_lendings_tool_id'), 'lendings', ['tool_id'], unique=False)
    op.create_index(op.f('ix_lendings_worker_id'), 'lendings', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lendings_worker_id'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_tool_id'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_returned_at'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_lent_at'), table_name='lendings')
    op.drop_index(op.f('ix_lendings_department_id'), table_name='lendings')
    op.drop_table('lendings')
    op.drop_index(op.f('ix_consumable_usages_worker_id'), table_name='consumable_usages')
    op.drop_index(op.f('ix_consumable_usages_used_at'), table_name='consumable_usages')
    op.drop_index(op.f('ix_consumable_usages_consumable_id'), table_name='consumable_usages')
    op.drop_table('consumable_usages')
    op.drop_index(op.f('ix_workers_department_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_barcode'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_department_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_barcode'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_consumables_department_id'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_barcode'), table_name='consumables')
    op.drop_table('consumables')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
